### PR TITLE
introduced a NET_DHCP_RETRY variable to correctly use the "-t" option…

### PR DESCRIPTION
**Pull request by jens-maus**
… of udhcpc. The old NET_DHCP_TIMEOUT variable is now used for the -T option defining the time between each timeout.

### CODE REVIEW

**Comment by Thinstation** [comment]
We need to set a default for that variable in thinstation.defaults, so that it always works even if it's not defined anywhere else, but looks good.

**Comment by jens-maus** [comment]
Yes, indeed. I forgot about thinstation.defaults. so please correct that after merging my pull request.

**Comment by jens-maus** [comment]
Any chance of getting this (and the others) pull request merged?

**Comment by Doncuppjr** [comment]
Sure, just finish up the pull request with that default variable.  

    On Tuesday, July 26, 2016 12:31 AM, Jens Maus <notifications@github.com> wrote:
 

 Any chance of getting this (and the others) pull request merged?—

**Comment by jens-maus** [comment]
Ok done. So please merge this PR and also the others waiting to be merged ;)

**Pull request merged**
