### PR TITLE
Add package locale-uk_UA

### PR DESCRIPTION
**Pull request by Dobromyr**
Hi!
I add package ts/build/packages/locale-uk_UA 
This is ukrainian locale for TS

Thanks!

### CODE REVIEW

**Comment by Thinstation** [comment]
A few little things, most of which I can help with. You need a .dna for the locale, so that any updates to the binaries will get made to new checkout of the package.
You changed the Readme to suggest this is a fork, but the pull request is going into mainline, not a fork.

**Comment by Dobromyr** [comment]
Sorry, I`m newbie in git

Where is my error in .dna?

P.S. Sorry for my English

**Comment by Doncuppjr** [comment]
You did put in the .dna, but you didn't clean_chroot before making commit, so bins were still in the package. I fixed and pushed.
Sent from Yahoo Mail on Android 
 
  On Mon, Jul 11, 2016 at 7:49 AM, Andriy Vartsabiuk<notifications@github.com> wrote:   
Sorry, I`m newbie in git

Where is my error in .dna?

P.S. Sorry for my English

**Comment by Dobromyr** [comment]
Thanks!

**Pull request merged**
