### PR TITLE
Multiple Fixes and Security Updates

### PR DESCRIPTION
**Pull request by ts-michaelk**
I kept the commits reasonably small and each commit generally describes what was done with each one.

### CODE REVIEW

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } 5.5?


Sent from Yahoo Mail for iPhone


On Saturday, March 25, 2017, 10:56 AM, ts-michaelk <notifications@github.com> wrote:


I kept the commits reasonably small and each commit generally describes what was done with each one.

You can view, comment on, or merge this pull request online at:

  https://github.com/Thinstation/thinstation/pull/213

Commit Summary
   
   - Updated Filezilla and wxgtk dependency
   - Discovered that Trash wasn't working with overlayfs in glib
   - Updating samba due to a critical security vulnerability
   - Resolving a known critical vulnerability in ImageMagick
   - Resolved a critical issue with NTP
   - Resolved a reported critical issue with inkscape
   - Some users asked for Pidgin's Off-the-Record (OTR) extension
   - Recompiled the XFCE general monitor (genmon) plugin with current XFCE
   - Fixed a link in p11-kit to resolve issue with library links during build
   - Updated FreeRDP to a newer "stable" build on the master branch
   - Update shadow for some security fixes and to add group shadow support if wanted
   - Modified ica init to handle changes to the configuration file locations
   - Added packages for Pidgin with SIPE and/or off-the-record plugins
   - Added configuration options for ethtool
   - In vmview make sure libmksvchanclient.so is a hard link
   - Updated samba-base for new samba version
   - A number of small fixes
   - Added a perl package to build images with core Perl
   - Adding the gstreamer bad and ugly modules to proprietary ports
   - Added cache files for pidgin extensions
   - Updated firmware to match current alsa
   - Added an updated approach for reducing the number of library links
   - Added parameter and support to use early microcode
   - Fixed Reload when switchuser is used
   - Include sessions in icon sorting by metrics and allow disabling suspend
   - Added some directory permission fixes and link redundant openssl libs
   - Consolidated the users and groups to remove some unused, match build env, and
   - Added a hook to run alternate instructions to load .pkg archive
   - Added conf file for ethtool
   - Recompiled rdesktop with updated dependencies
   - Merge branch 'master' of Thinstation/thinstation
   - Removed duplicate freerdp port created by merge

File Changes
   
   -  M ts/bin/repackage (32) 
   -  M ts/build/boot-images/initrd/initrd.devices (0) 
   -  M ts/build/build (97) 
   -  M ts/build/build.conf.example (2) 
   -  M ts/build/conf/default/build.conf.example (2) 
   -  A ts/build/conf/ethtool.conf.sample (7) 
   -  M ts/build/packages/base/bin/pkg (4) 
   -  M ts/build/packages/base/build/finalize (24) 
   -  M ts/build/packages/base/etc/group (78) 
   -  M ts/build/packages/base/etc/passwd (58) 
   -  M ts/build/packages/base/etc/profile (14) 
   -  A ts/build/packages/ethtool/.gitignore (3) 
   -  A ts/build/packages/ethtool/build/conf/90ethtool (7) 
   -  M ts/build/packages/ethtool/build/extra/etc/init.d/ethtool (4) 
   -  M ts/build/packages/file-roller/.dna (1) 
   -  M ts/build/packages/firefox/build/finalize (1) 
   -  M ts/build/packages/firefox/etc/TS.default/prefs.tpl (3) 
   -  A ts/build/packages/fonts-TTF-MS/.gitignore (2) 
   -  M ts/build/packages/gnome-core/build/extra/etc/init.d/gnome-core.init (8) 
   -  A ts/build/packages/gst-plugins-bad/.dna (3) 
   -  A ts/build/packages/gst-plugins-bad/.gitignore (2) 
   -  A ts/build/packages/gst-plugins-bad/build/install (9) 
   -  A ts/build/packages/gst-plugins-bad/build/remove (4) 
   -  A ts/build/packages/gst-plugins-bad/dependencies (1) 
   -  A ts/build/packages/gst-plugins-ugly/.dna (3) 
   -  A ts/build/packages/gst-plugins-ugly/.gitignore (2) 
   -  A ts/build/packages/gst-plugins-ugly/build/install (9) 
   -  A ts/build/packages/gst-plugins-ugly/build/remove (4) 
   -  A ts/build/packages/gst-plugins-ugly/dependencies (1) 
   -  M ts/build/packages/ica/build/extra/etc/init.d/ica.init (18) 
   -  M ts/build/packages/java/build/install (2) 
   -  M ts/build/packages/overlayfs/etc/rc0.d/00overlayfs (1) 
   -  A ts/build/packages/p11-kit/.gitignore (4) 
   -  A ts/build/packages/perl/.dna (3) 
   -  A ts/build/packages/perl/.gitignore (3) 
   -  A ts/build/packages/perl/build/install (9) 
   -  A ts/build/packages/perl/build/remove (4) 
   -  A ts/build/packages/perl/dependencies (1) 
   -  A ts/build/packages/pidgin-otr/.dna (3) 
   -  A ts/build/packages/pidgin-otr/build/install (9) 
   -  A ts/build/packages/pidgin-otr/build/remove (4) 
   -  A ts/build/packages/pidgin-otr/dependencies (1) 
   -  A ts/build/packages/pidgin-sipe/.dna (3) 
   -  A ts/build/packages/pidgin-sipe/build/install (9) 
   -  A ts/build/packages/pidgin-sipe/build/remove (4) 
   -  A ts/build/packages/pidgin-sipe/dependencies (1) 
   -  M ts/build/packages/pulseaudio/build/finalize (6) 
   -  M ts/build/packages/samba-base/.dna (2) 
   -  M ts/build/packages/samba-base/etc/init.d/samba-base (2) 
   -  M ts/build/packages/samba-base/lib/smb.conf.tpl (4) 
   -  M ts/build/packages/switchuser/sbin/session (11) 
   -  M ts/build/packages/systemd/build/install (2) 
   -  M ts/build/packages/vmviewpcoip/build/extra/etc/init.d/vmview.init (4) 
   -  M ts/build/packages/vmviewpcoip/build/install (1) 
   -  A ts/build/packages/wine/.gitignore (4) 
   -  M ts/build/packages/xfwm4/build/extra/etc/xfwm4.functions (50) 
   -  M ts/ports/binary-core/firmware-alsa/.footprint (8) 
   -  M ts/ports/binary-core/firmware-alsa/.gitignore (2) 
   -  M ts/ports/binary-core/firmware-alsa/.md5sum (2) 
   -  M ts/ports/binary-core/firmware-alsa/Pkgfile (2) 
   -  M ts/ports/binary-core/firmware-zd1211/.gitignore (2) 
   -  M ts/ports/binary-core/firmware-zd1211/.md5sum (2) 
   -  M ts/ports/binary-core/firmware-zd1211/Pkgfile (2) 
   -  A ts/ports/components/libotr/.footprint (36) 
   -  A ts/ports/components/libotr/.md5sum (1) 
   -  A ts/ports/components/libotr/Pkgfile (19) 
   -  A ts/ports/components/libotr/libotr#4.1.0-1.pkg.tar.gz (0) 
   -  A ts/ports/components/pidgin-otr/.footprint (5) 
   -  A ts/ports/components/pidgin-otr/.md5sum (1) 
   -  A ts/ports/components/pidgin-otr/Pkgfile (24) 
   -  A ts/ports/components/pidgin-otr/pidgin-otr#4.0.1-1.pkg.tar.gz (0) 
   -  M ts/ports/contrib/filezilla/.footprint (354) 
   -  M ts/ports/contrib/filezilla/.md5sum (2) 
   -  M ts/ports/contrib/filezilla/Pkgfile (43) 
   -  A ts/ports/contrib/filezilla/filezilla#3.16.1-1.pkg.tar.xz (0) 
   -  D ts/ports/contrib/filezilla/filezilla#3.7.4.1-1.pkg.tar.gz (0) 
   -  M ts/ports/contrib/inkscape/.footprint (1) 
   -  M ts/ports/contrib/inkscape/.md5sum (2) 
   -  M ts/ports/contrib/inkscape/Pkgfile (2) 
   -  R ts/ports/contrib/inkscape/inkscape#0.48.5-1.pkg.tar.gz (0) 
   -  A ts/ports/contrib/libfilezilla/.footprint (34) 
   -  A ts/ports/contrib/libfilezilla/.md5sum (1) 
   -  A ts/ports/contrib/libfilezilla/Pkgfile (22) 
   -  A ts/ports/contrib/libfilezilla/libfilezilla#0.5.3-1.pkg.tar.xz (0) 
   -  M ts/ports/contrib/ntp/.footprint (3) 
   -  M ts/ports/contrib/ntp/.md5sum (2) 
   -  M ts/ports/contrib/ntp/Pkgfile (2) 
   -  D ts/ports/contrib/ntp/ntp#4.2.8p1-1.pkg.tar.gz (0) 
   -  A ts/ports/contrib/ntp/ntp#4.2.8p9-1.pkg.tar.gz (0) 
   -  M ts/ports/contrib/rdesktop/rdesktop#1.8.3-1.pkg.tar.gz (0) 
   -  M ts/ports/contrib/wxgtk/.footprint (1455) 
   -  M ts/ports/contrib/wxgtk/.md5sum (2) 
   -  M ts/ports/contrib/wxgtk/Pkgfile (33) 
   -  D ts/ports/contrib/wxgtk/wxgtk#2.8.12-1.pkg.tar.gz (0) 
   -  A ts/ports/contrib/wxgtk/wxgtk#3.0.2-1.pkg.tar.xz (0) 
   -  A ts/ports/contrib/wxgtk/wxgtk-freeze.patch (48) 
   -  M ts/ports/core/shadow/.footprint (6) 
   -  M ts/ports/core/shadow/.md5sum (2) 
   -  M ts/ports/core/shadow/Pkgfile (7) 
   -  D ts/ports/core/shadow/shadow#4.1.4.3-1.pkg.tar.gz (0) 
   -  A ts/ports/core/shadow/shadow#4.2.1-1.pkg.tar.xz (0) 
   -  M ts/ports/opt/freerdp/.footprint (11) 
   -  M ts/ports/opt/freerdp/.md5sum (1) 
   -  M ts/ports/opt/freerdp/Pkgfile (13) 
   -  D ts/ports/opt/freerdp/freerdp#2.0-dev-master.pkg.tar.xz (0) 
   -  A ts/ports/opt/freerdp/freerdp#2.0-master.pkg.tar.gz (0) 
   -  A ts/ports/opt/freerdp/freerdp-2.0.0-tprdp.patch (11) 
   -  M ts/ports/opt/glib/.md5sum (1) 
   -  A ts/ports/opt/glib/0001-Fix-trashing-on-overlayfs.patch (61) 
   -  M ts/ports/opt/glib/Pkgfile (4) 
   -  D ts/ports/opt/glib/glib#2.32.4-1.pkg.tar.gz (0) 
   -  A ts/ports/opt/glib/glib#2.32.4-1.pkg.tar.xz (0) 
   -  M ts/ports/opt/imagemagick/.footprint (77) 
   -  M ts/ports/opt/imagemagick/.md5sum (2) 
   -  M ts/ports/opt/imagemagick/Pkgfile (4) 
   -  D ts/ports/opt/imagemagick/imagemagick#6.8.9-0-1.pkg.tar.gz (0) 
   -  A ts/ports/opt/imagemagick/imagemagick#6.9.6-6-1.pkg.tar.gz (0) 
   -  M ts/ports/opt/ldb/.footprint (12) 
   -  M ts/ports/opt/ldb/.md5sum (2) 
   -  M ts/ports/opt/ldb/Pkgfile (2) 
   -  D ts/ports/opt/ldb/ldb#1.1.26-1.pkg.tar.xz (0) 
   -  A ts/ports/opt/ldb/ldb#1.1.29-1.pkg.tar.xz (0) 
   -  M ts/ports/opt/samba/.footprint (463) 
   -  M ts/ports/opt/samba/.md5sum (2) 
   -  M ts/ports/opt/samba/Pkgfile (4) 
   -  R ts/ports/opt/samba/samba#4.5.5-1.pkg.tar.xz (0) 
   -  M ts/ports/opt/talloc/.footprint (16) 
   -  M ts/ports/opt/talloc/.md5sum (2) 
   -  M ts/ports/opt/talloc/Pkgfile (2) 
   -  D ts/ports/opt/talloc/talloc#2.1.7-1.pkg.tar.xz (0) 
   -  A ts/ports/opt/talloc/talloc#2.1.8-1.pkg.tar.xz (0) 
   -  M ts/ports/opt/tdb/.footprint (6) 
   -  M ts/ports/opt/tdb/.md5sum (2) 
   -  M ts/ports/opt/tdb/Pkgfile (2) 
   -  A ts/ports/opt/tdb/tdb#1.3.12-1.pkg.tar.xz (0) 
   -  D ts/ports/opt/tdb/tdb#1.3.9-1.pkg.tar.xz (0) 
   -  M ts/ports/opt/tevent/.footprint (6) 
   -  M ts/ports/opt/tevent/.md5sum (2) 
   -  M ts/ports/opt/tevent/Pkgfile (2) 
   -  D ts/ports/opt/tevent/tevent#0.9.28-1.pkg.tar.xz (0) 
   -  A ts/ports/opt/tevent/tevent#0.9.31-1.pkg.tar.xz (0) 
   -  A ts/ports/proprietary/gst-plugins-bad/.footprint (293) 
   -  A ts/ports/proprietary/gst-plugins-bad/.md5sum (1) 
   -  A ts/ports/proprietary/gst-plugins-bad/Pkgfile (31) 
   -  A ts/ports/proprietary/gst-plugins-ugly/.footprint (36) 
   -  A ts/ports/proprietary/gst-plugins-ugly/.md5sum (1) 
   -  A ts/ports/proprietary/gst-plugins-ugly/Pkgfile (28) 
   -  M ts/ports/xfce/xfce4-genmon-plugin/xfce4-genmon-plugin#3.4.0-1.pkg.tar.gz (0) 
   -  M ts/ports/xorg-opt/p11-kit/.footprint (2) 
   -  M ts/ports/xorg-opt/p11-kit/Pkgfile (2) 
   -  M ts/ports/xorg-opt/p11-kit/p11-kit#0.22.1-1.pkg.tar.gz (0) 
   -  M ts/unwind_cache/file-roller.turbo (7) 
   -  A ts/unwind_cache/gst-plugins-bad.turbo (2) 
   -  A ts/unwind_cache/gst-plugins-ugly.turbo (2) 
   -  A ts/unwind_cache/perl.turbo (2) 
   -  A ts/unwind_cache/pidgin-otr.turbo (2) 
   -  A ts/unwind_cache/pidgin-sipe.turbo (2) 
   -  M ts/unwind_cache/samba-base.turbo (9) 
   -  M ts/wind_cache/file-roller.turbo (3) 
   -  A ts/wind_cache/gst-plugins-bad.turbo (2) 
   -  A ts/wind_cache/gst-plugins-ugly.turbo (2) 
   -  A ts/wind_cache/perl.turbo (2) 
   -  A ts/wind_cache/pidgin-otr.turbo (2) 
   -  A ts/wind_cache/pidgin-sipe.turbo (2) 
   -  M ts/wind_cache/samba-base.turbo (4) 

Patch Links:
   
   - https://github.com/Thinstation/thinstation/pull/213.patch
   - https://github.com/Thinstation/thinstation/pull/213.diff

**Comment by trentasis** [comment]
Hi @ts-michaelk 

Great job!
One question, about freerdp-2.0.0-tprdp.patch  in freerdp, what is this?

Thanks

**Comment by ts-michaelk** [comment]
It's for VMware Horizon Client when using RDP mode.  It's for printer
redirection I think.
When you unpack VMware, there's the patch in there.  It was for 1.1 or 1.2
because that's what a bunch of OS are still using - I just fixed it up to
work with latest.  It's a pretty easy/straightforward patch.

Trentasis - sorry - I did see that I might conflict with what you were
doing as we both needed a FreeRDP update to get a more stable version going.

**Comment by trentasis** [comment]
Hi @ts-michaelk 

Thanks for your information

**Pull request merged**
