### PR TITLE
Mount Userconf by PARTLABEL

### PR DESCRIPTION
**Pull request by Se7ven**
Good day!
I see in the script locale-install that a PARTLABEL is being created, but is not used anywhere else.
I propose to fix the script scsi.sh so that it checks not only the LABEL but also the PARTLABEL when mounting.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
There is no need to commit changes to ts/build/thinstation.conf.buildtime . Please roll back that change. scsi.sh looks o.k.

**Comment by Se7ven** [comment]
But without changes conf file automount doesn`t work on first build and installation. System searches LABEL=storage but we have only PARTLABEL=Thinstation_Userconf.
I as a new user of Thinstation was confused cause I need labeled sda2 partition. 
In this case any new user give worked solution without any manual fixes and steps.

BTW busybox mount doesn`t support x-mount.mkdir and this also confused me.

Maybe there is other way to fix automount Userconf partition without change buildtime conf file.

**Comment by Thinstation** [comment]
You can change your thinstation.conf.buildtime, but I don't need your version. You chose to label your partitions, and you picked that schema. Let everyone else choose their own schema.

**Comment by Se7ven** [comment]
I reverted changes a builtime config file. 
Is it ok?

**Pull request merged**
