### PR TITLE
Update ocsinventory to 1.6.4

### PR DESCRIPTION
**Pull request by trentasis**
Latest stable version 1.6.4

### CODE REVIEW

**Comment by trentasis** [comment]
Any scheduled date when could be added?

**Comment by Doncuppjr** [comment]
Maybe soon, working on an update to xorg gnome and xfce for 6.1 at this moment.


Sent from Yahoo Mail for iPhone


On Saturday, May 19, 2018, 1:46 PM, trentasis <notifications@github.com> wrote:


Any scheduled date when could be added?

**Comment by trentasis** [comment]
ok, can you add to branch 5.5?  this is a minor update
I Think that doesn't generate any conflict

**Comment by Thinstation** [comment]
I updated the binaries, but I need you to just submit a PR for the package changes.

**Pull request closed without merging**
