### PR TITLE
Correction of options Admin password and wget

### PR DESCRIPTION
**Pull request by shweew**
The option - N is not supported by wget BusyBox.

### CODE REVIEW

**Comment by shweew** [comment]
In Thinstation BusyBox is usually used if to remove - N, then will work anyway. If to leave an option - N, then to register full wget in dependencies.
https://github.com/Thinstation/thinstation/blob/6.1-Stable/ts/build/packages/openkiosk/build/conf/50openkiosk 
https://github.com/Thinstation/thinstation/blob/6.1-Stable/ts/build/conf/openkiosk.conf.sample
SESSION_#_OPENKIOSK_ADMIN_PASS=

**Comment by Thinstation** [comment]
Yes., if you want to submit a PR for using the busybox wget explicitly, I
would accept that.

**Comment by Thinstation** [comment]
O.k. the only issue I see with this, is that you didn't create ports that build the binaries that you left in /build/packages. 

Where do those binaries come from?

**Comment by shweew** [comment]
There are no ports, there were drivers builded for linux on the website of the vendor.
Checked, works.

**Comment by shweew** [comment]
Cancel drivers of rutoken and ASEDrive IIIe USB and ASEDrive IIIe USB KB, they are 32 Bit.
Checked in ts_5.6.
Sorry.

**Comment by Thinstation** [comment]
why did you delete ts/build/build.conf.example?

**Comment by shweew** [comment]
Do not accept change, except xdmcp-connect.

**Comment by shweew** [comment]
I close PR as there are a lot of errors, I will rebuild drivers I will create new PR.

**Pull request closed without merging**
