### PR TITLE
Stop ICA 13.1 presenting the EULA on launch

### PR DESCRIPTION
**Pull request by justinchevrier**

### CODE REVIEW

**Comment by Thinstation** [comment]
Yes, that is a way to do that, but it's not the place of the thinstation project to do that for people. It in fact might create some real obstacles for the project.

**Comment by Thinstation** [comment]
You could add something to the wiki.

**Comment by justinchevrier** [comment]
Sure, I can appreciate that shortcutting the EULA display/acceptance is not a good idea. During the initial build when the ICA client is pulled in Thinstation used to have you step through a few options (presented from the ICA client) including accepting the EULA. The current version seems to auto fill that in for you (or it seemed to for me). In the previous versions after accepting the EULA during the build I never saw the EULA on the client systems. With the current builds it presents the EULA on every launch of the client. Can we revert back to having users step through the ICA client setup questions (or at least the EULA question), then based on the answer to that question create/copy the '.eula_accepted' file?

**Comment by Thinstation** [comment]
Send me a patch

**Pull request closed without merging**
