### PR TITLE
Installer Package now reusable

### PR DESCRIPTION
**Pull request by N0odlez**
I have seen many requests over the mailing lists and also on GitHub on how to install Thinstation to a Hard Drive. I have also had this question for quite some time. So instead of sitting and waiting ive gone ahead and adapted the Installer Package so that it can be reused in any ones project to install their thinstation archive on the the hard drive.

There are some main Variables added:
INSTALLER_WEB_ADDRESS
INSTALLER_ARCHIVE_NAME
INSTALLER_DEV
INSTALLER_READ_ME

All of these can be used to make a usable installer package. I have edited the installer configs to show how the default setup would be done for the ThinStation releases.

I hope this is welcomed with open arms and please do suggest an changes that you think could be done or if this can be done a better way.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Your grabbing the right archive by name, but your still only unwinding it if it's named thindev-default #line 120

**Comment by N0odlez** [comment]
Well spotted. I will change tomorrow to the INSTALLER_ARCHIVE_NAME var.

**Comment by N0odlez** [comment]
Changes have been made and i have also formatted the file so it can be read easier in the future.

**Comment by Thinstation** [comment]
Nasty.

**Comment by N0odlez** [comment]
?

**Comment by Thinstation** [comment]
You didn’t test a single line of that code.

**Pull request merged**
