### PR TITLE
added pulseaudio package

### PR DESCRIPTION
**Pull request by tohan4**
Added commented out pulse audio package to build.conf.exmple
required for USB headsets to work with Horizon View Client 4.6.0 and Skype Virtualisation Pack (media-provider)

### CODE REVIEW

**Comment by Doncuppjr** [comment]
We could possibly make a new profile for VMware view. I don’t want to mess with default, it’s supposed to be the best starting point.....generally. Why doesn’t view work with pulse?

**Comment by tohan4** [comment]
What naming convention do you want to use for the Horizon View Client 4.6.0?
pulseaudio was not in build.conf.example as a package parameter so not able to be built

**Comment by Doncuppjr** [comment]
I usually keep example configurations in the /ts/build/conf/<desired result>/ like folders.I don't know how current they are, but it does look like I have a few existing configs for View.Do these work?Thinstation/thinstation


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Thinstation/thinstation

thinstation - A framework for making thin and light Linux based images for x86 based machines and thinclients.
 |

 |

 |


Thinstation/thinstation


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Thinstation/thinstation

thinstation - A framework for making thin and light Linux based images for x86 based machines and thinclients.
 |

 |

 |


Do you know that View won't work with pulse?


    On Friday, November 10, 2017, 8:49:03 PM PST, tohan4 <notifications@github.com> wrote:  
 
 
What naming convention do you want to use for the Horizon View Client 4.6.0?
pulseaudio was not in build.conf.example as a package parameter so not able to be built

**Comment by tohan4** [comment]
added package vmhorizonclient. Changed build.url to point to vmware website. Added t620 machine profile.

**Comment by tohan4** [comment]
The 4.6.0 Horizon Client includes the new media-provider feature (Skype Virtualisation Pack) which works with Horizon Agent 7.2 and above. It has the PCoIP and Blast (H264) protocols.

**Comment by Thinstation** [comment]
O.k., but what I mean is, relative to thinstation packages, why did you make a new package instead of updating one of the existing view packages?

**Comment by tohan4** [comment]
Donald asked me to so it doesn't interfere with the existing vmviewpcoip package. (this package name doesn't suit the set of features in the current horizon client also VMware have renamed their product to Horizon Client from View Client as of version 4 ish)
There will be more changes coming for the vmhoirzonclient package to remove some redundant code which is no longer required (probably next week) which could break the vmviewpcoip package.

**Pull request merged**
