### PR TITLE
Update pcsc/ccid, remote desktop clients and ocsinventory

### PR DESCRIPTION
**Pull request by trentasis**
Latest pcsc, ccid and pcsc-tools
Latest rdesktop
Latest freerdp 
Latest ocsinventory

### CODE REVIEW

**Comment by trentasis** [comment]
Hi,



Can't take the changes to thinstation.defaults. --> Where is the issue, 30 retires will be a solution for  problems related with Spanning tree with multiple switchs, Waht do you need to allow this change?

Why Pkgfile.orig ? --> Sorry, can be deleted o wait until 1.8.4 rdesktop, PKgfile is different
Pcsc-tools needs a /use prefix --> I don't understand what is the problem, but, pcsc-tools can be ignored and revert to previou version, latest pcscd and ccid are needed to solve probems but pcsc-tools not for normal usage. If you give me detail I'll try to solve the problem.

Thanks!

**Comment by Doncuppjr** [comment]
30 is too long for a default. This can be overridden in . Buildtime


Sent from Yahoo Mail for iPhone


On Saturday, July 22, 2017, 11:39 AM, trentasis <notifications@github.com> wrote:


Hi,

Can't take the changes to thinstation.defaults. --> Where is the issue, 30 retires will be a solution for problems related with Spanning tree with multiple switchs, Waht do you need to allow this change?

Why Pkgfile.orig ? --> Sorry, can be deleted o wait until 1.8.4 rdesktop, PKgfile is different
Pcsc-tools needs a /use prefix --> I don't understand what is the problem, but, pcsc-tools can be ignored and revert to previou version, latest pcscd and ccid are needed to solve probems but pcsc-tools not for normal usage. If you give me detail I'll try to solve the problem.

Thanks!

**Comment by trentasis** [comment]
About 30 retries is because I remember mutiple users are reporting tftp errors related with this error, and this allows to retry ever 3 seconds, until is up... not always 30 retries or less will be made... usually in afew retries will work.
And 20 will be good?

What is the problem with pcsc tools?

Thanks

**Comment by Doncuppjr** [comment]
Suggest the option in the conf help file, as a solution to spanning tree. The default needs to be something that boots quickly without a good network. 


Sent from Yahoo Mail for iPhone


On Saturday, July 22, 2017, 12:30 PM, trentasis <notifications@github.com> wrote:


About 30 retries is because I remember mutiple users are reporting tftp errors related with this error, and this allows to retry ever 3 seconds, until is up... not always 30 retries or less will be made... usually in afew retries will work.
And 20 will be good?

What is the problem with pcsc tools?

Thanks

**Comment by trentasis** [comment]
ok, changed to default value 3
Correct?

Thanks!

**Comment by trentasis** [comment]
@Doncuppjr 
Solved 3 items, can you push this PR to 5.5 Stable?
If you  detecte any other issue you can inform

**Comment by Thinstation** [comment]
It has conflicts.

**Comment by trentasis** [comment]
ocs inventory conflict can be  replaced with latest version 1.5.1, I don't have permission, can you solve when you accept pr?

Thanks

**Comment by trentasis** [comment]
Thanks, and sorry, I'm new with git usage...

**Comment by Doncuppjr** [comment]
No worries.

    On Tuesday, July 25, 2017 11:19 PM, trentasis <notifications@github.com> wrote:
 

 Thanks, and sorry, I'm new with git usage...—

**Pull request merged**
