### PR TITLE
Update thinstation.defaults

### PR DESCRIPTION
**Pull request by trentasis**
NET_DHCP_RETRY=30, in some configuration spanning tree mode can delay (+50 seconds), and then dhcp fail

### CODE REVIEW

**Comment by Thinstation** [comment]
Uhh, can we put that in a knowledge base instead of making everybody wait that long to power up when the network is bad?

**Comment by trentasis** [comment]
I understand that with default timeout, 3, and this value 30 thiswill retry every 3 seconds until 90 seconds... correct?

**Comment by Thinstation** [comment]
Sounds about right.

**Comment by trentasis** [comment]
OK, now we are testing this and other changes... I'll try to report the
results after some days...

Thanks

2017-07-04 19:40 GMT+02:00 Thinstation <notifications@github.com>:

> Sounds about right.
>

**Comment by trentasis** [comment]
It seems that works, can you commit?

Thanks

**Pull request closed without merging**
