### PR TITLE
update package ocsinventory-agent

### PR DESCRIPTION
**Pull request by trentasis**

### CODE REVIEW

**Comment by Thinstation** [comment]
I went about this a different way. I hope you don't mind.

**Comment by trentasis** [comment]
Sorry but this changes are not correct, you have configured official agent that is not supported (requires some perl modules not supported and also generate a high disk and ram usage) with thinstation, please roll backup to previous version..

Thanks

**Comment by Thinstation** [comment]
One of the things I have really tried to do with the TS project is keep third party binaries out of the repo. OpenSource and Free, or not. If you get me the URL from where to download these un-official agent bins, I will try and hook them in.

**Comment by trentasis** [comment]
url is avialabe from /ts/build/conf/ocsinventory.conf.sample
 and is

 https://github.com/jackburton79/agent

I hope that this can help...

I have tried to make package like freerdp as template but without success... I don't know where is the problem...

If it is possible can you detail for future new package how do you create ocs package?

thanks

**Comment by trentasis** [comment]
With you latest versión and two small fixes,  chmox +x oceinventory.ini and
remove an old softlink to rc5 Works perfect!!
Please push this two changes

Thanks

2016-05-30 17:59 GMT+02:00 Thinstation <notifications@github.com>:

**Pull request closed without merging**
