### PR TITLE
Add and update packages

### PR DESCRIPTION
**Pull request by shweew**
Add xdmcp-connect, xmenu, AseIIIeUSB & RutokenS drivers packages.
Update OpenKiosk, rdesktop, vboxguest downloads url.
Fix OpenKiosk init script.

### CODE REVIEW

**Review by shweew — COMMENTED** [review]
modified: add wget in ts/build/packages/openkiosk/dependencies

**Review by ghost — COMMENTED** [review]
Why did you disable chrome?

**Comment by shweew** [comment]
I usually do not use it, forgot to include back.

**Review by ghost — COMMENTED** [review]
How would this xdmcp package integrate with systemd?

**Comment by shweew** [comment]
init does not work unless any more?

**Comment by Thinstation** [comment]
6.1 is systemd based, so init files in init.d need to be called by systemd
unit files. Also, it looks like your just kinda starting X, is that the
best way to do that?

**Comment by shweew** [comment]
Yes, it is the standard procedure of connection to xdmcp to the server, I will make systemd today.

**Comment by shweew** [comment]
Add xdmcp-connect systemd unit

**Comment by shweew** [comment]
PR is not suitable for commit?

**Comment by Doncuppjr** [comment]
I’m still dealing with the last PR another user sent me. Neither is perfect, but I’ll try and make them work.


Sent from Yahoo Mail for iPhone


On Saturday, February 23, 2019, 9:13 PM, Dmitriy Shweew <notifications@github.com> wrote:


PR is not suitable for commit?

**Review by ghost — APPROVED** [review]

**Pull request merged**
