### PR TITLE
Correction of options Admin password and wget

### PR DESCRIPTION
**Pull request by shweew**

### CODE REVIEW

**Comment by shweew** [comment]
The option - N is not supported by wget

**Comment by Doncuppjr** [comment]
The BusyBox version does not, but full size wget does. Might want to specify which one you are going to use. 
Are you sure about that password edit? Is that just a preference?


Sent from Yahoo Mail for iPhone


On Sunday, February 17, 2019, 11:50 PM, Dmitriy Shweew <notifications@github.com> wrote:


The option - N is not supported by wget

**Comment by shweew** [comment]
In Thinstation BusyBox is usually used if to remove - N, then will work
anyway.
https://github.com/Thinstation/thinstation/blob/6.1-Stable/ts/build/packages/openkiosk/build/conf/50openkiosk

In the 10th line it is written
 SESSION_#_OPENKIOSK_*ADMIN_PASS*
It is necessary to correct or there or as I offered.

вт, 19 февр. 2019 г. в 02:02, Donald A. Cupp Jr. <notifications@github.com>:

> The BusyBox version does not, but full size wget does. Might want to
> specify which one you are going to use.
> Are you sure about that password edit? Is that just a preference?
>
>
> Sent from Yahoo Mail for iPhone
>
>
> On Sunday, February 17, 2019, 11:50 PM, Dmitriy Shweew <

**Comment by shweew** [comment]
https://github.com/Thinstation/thinstation/blob/6.1-Stable/ts/build/conf/openkiosk.conf.sample
In the file too option SESSION_#_OPENKIOSK_*ADMIN_PASS*=
If to leave an option - N, then to register full wget in dependencies

вт, 19 февр. 2019 г. в 02:02, Donald A. Cupp Jr. <notifications@github.com>:

> The BusyBox version does not, but full size wget does. Might want to
> specify which one you are going to use.
> Are you sure about that password edit? Is that just a preference?
>
>
> Sent from Yahoo Mail for iPhone
>
>
> On Sunday, February 17, 2019, 11:50 PM, Dmitriy Shweew <

**Pull request closed without merging**
