### PR TITLE
ViewHorizon Update for python3,

### PR DESCRIPTION
**Pull request by rohrbachger**
Newer Horizon View Client 23xx needs gcc12 and also the python3 for setup,with python 2 where issues
Here included only the vmview package fix, without gcc12.

### CODE REVIEW

**Comment by Doncuppjr** [comment]
If you are using a pip3.freeze file, you don't need to make ports......

**Comment by Doncuppjr** [comment]
I say this, because I hate having python ports, and I try and keep it down to just the ones that are needed to compile other packages. I prefer for the image building system to use .freeze files, then we don't have to dink around with version in the directory name problem.

**Comment by rohrbachger** [comment]
I understand would you mean. Is there any sample available how it works with pip3.freeze in TS?
This sounds much easier as with ports. I was really proud to get it working, but you have much more experience.
The first commit for horizon view does not need the unixodbc, freetds, pyodbc and pywinrm.
So it will try to revoke this and make pip3.freeze packages.

Iḿ still a git beginner.

**Comment by rohrbachger** [comment]
I will pull a new requerst for gcc12 port and a different for the view client update.

**Comment by Doncuppjr** [comment]
I was not ignoring this, but if the new client requires a new gcc, then that needs to be part of the merge. Thank you for the contribution.

**Comment by rohrbachger** [comment]
That is stopping me, large file.
I did not figured yet out, how to solve this.

root@Desktop:/GRPROG/thinstation-31/ts/ports/core/gcc# git commit
[6.2-Stable 2602e18] gcc 12.2 git lfs needed
 1 file changed, 1 insertion(+)
 create mode 100644 ts/ports/core/gcc/.gitattributes
root@Desktop:/GRPROG/thinstation-31/ts/ports/core/gcc# git push
Username for 'https://github.com': rohrbachger
Password for 'https://rohrbachger@github.com': 
Objekte aufzählen: 21, fertig.
Zähle Objekte: 100% (21/21), fertig.
Delta-Kompression verwendet bis zu 4 Threads.
Komprimiere Objekte: 100% (15/15), fertig.
Schreibe Objekte: 100% (15/15), 106.64 MiB | 1.35 MiB/s, fertig.
Gesamt 15 (Delta 10), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
remote: Resolving deltas: 100% (10/10), completed with 5 local objects.
**remote: error: Trace: 85dfd853e718965dd3f3df914e51b602358f9e65022507cf0417b34a5d644d41
remote: error: See https://gh.io/lfs for more information.
remote: error: File ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz is 106.60 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.**
To https://github.com/rohrbachger/thinstation.git
 ! [remote rejected] 6.2-Stable -> 6.2-Stable (pre-receive hook declined)
error: Fehler beim Versenden einiger Referenzen nach 'https://github.com/rohrbachger/thinstation.git'

**Comment by Thinstation** [comment]
Use the shrink command

**Comment by rohrbachger** [comment]
The gcc file is already too large.
Do you mean git shrink? Did not found somethink  for this.

root@Desktop:/GRPROG/thinstation-31/ts/ports/core/gcc# ls -l
-rw-r--r-- 1 root root 111780192 Okt 21 15:39 gcc#12.2.0-1.pkg.tar.xz
-rw-r--r-- 1 root root      5636 Okt 21 15:39 Pkgfile

**Comment by Thinstation** [comment]
‘shrink gcc’

**Comment by rohrbachger** [comment]
Got it, but result 0 byte is not okay.
The error is pointing to an memory issue, machine has enough..


root@TS_chroot]/# shrink gcc
+ port=gcc
++ prt-get printf %v --filter=gcc
+ version=12.2.0
++ prt-get printf %r --filter=gcc
+ release=1
++ prt-get path gcc
+ path=/ts/ports/core/gcc
+ '[' -e /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.gz ']'
+ '[' -e /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz ']'
+ sarchive=/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz
+ darchive=/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz
+ '[' -z /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz ']'
+ '[' -z /ts/ports/core/gcc ']'
+ '[' -e /tmp/shrink ']'
+ mkdir -p /tmp/shrink
+ mount -t tmpfs -o size=1G tmpfs /tmp/shrink
+ tar -xf /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz -C /tmp/shrink
++ du -sb /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz
++ cut -f1
+ oldsize=111780192
+ cd /tmp/shrink
+ tar -c usr
+ xz -9 --lzma2=dict=max
**xz: (stdin): Cannot allocate memory**
++ du -sb /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz.new
++ cut -f1
+ newsize=0
+ '[' 111780192 -gt 0 ']'
+ cp /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz.new /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz
+ rm /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz.new
+ cd /
+ umount /tmp/shrink
+ rmdir /tmp/shrink


[root@TS_chroot]/ts/ports/core/gcc# ls -l
total 8
-rw-r--r-- 1 root root 5636 Oct 21 13:39 Pkgfile
-rw-r--r-- 1 root root    **0** Oct 21 17:04 gcc#12.2.0-1.pkg.tar.xz

**Comment by Thinstation** [comment]
You need more RAM

**Comment by rohrbachger** [comment]
machine has 8GB RAM, I restarted, still the same.
Iḿ running on ubuntu, maybe this makes a difference.

**Comment by Thinstation** [comment]
I give my VM’s 32gb. You could try without using a RAM disk. Edit the
shrink command.

**Comment by rohrbachger** [comment]
I made some unsuccessful experiments with shrink.
I ordered some more memory,...

**Comment by Doncuppjr** [comment]
The main thing that shrink does, is utilize the maximum compression mode of xz to make s smaller archive. This works well when dealing with a rather large archive that can benefit from the bigger dictionary. This uses quite a bit of memory though, so not an everyday kind of thing. It also makes a 1 gig ram disk, just for speed, but that usually is not what is getting in the way.
    On Tuesday, October 24, 2023 at 10:59:55 AM MDT, rohrbachger ***@***.***> wrote:  
 
 


I made some unsuccessful experiments with shrink.
I ordered some more memory,...

**Pull request closed without merging**
