### PR TITLE
Update Pkgfile

### PR DESCRIPTION
**Pull request by communitysteps**
Update Pkgfile removing references to freerdp-2.0.0-tprdp.patch 

From issue: https://github.com/Thinstation/thinstation/issues/289

This brings Pkgfile in line with similar change to 5.5-Stable, pulling FreeRDP from latest/master: https://github.com/Thinstation/thinstation/commit/10c965002bd76605bb60fd87ae32ab9c9b735299#diff-20c5fc0890f3dcdad96bf88199d1c41d

### CODE REVIEW

**Comment by alphafalcon** [comment]
I think the .patch file itself could be removed too or is it still in use somewhere?

**Comment by ts-michaelk** [comment]
The patch is for using RDP with VMware Horizon Client.
If you completely remove it, some redirection doesn't work.
I don't know if many users are using RDP with VMware and if it will even work with FreeRDP 2.0 versions.
Ultimately the issue is that FreeRDP 2.0 API is constantly changing, so this patch keeps needing to be updated.

**Comment by ts-michaelk** [comment]
We can upstream it and I can put it back later - I'm sure we'll have to rebuild FreeRDP when it's released if not sooner.  Nobody seems to be missing the patch since it's been knocked out of 5.5 for a while.

**Comment by Thinstation** [comment]
Sorry, other update got in the way of this one. Please fix and resubmit.

**Pull request closed without merging**
