### PR TITLE
New packages for central management and image deployment and fixes for ica to support StoreFront and more.

### PR DESCRIPTION
**Pull request by MarcusEyre**
¤ Added machine Acer Revo M1-601
¤ Added machine Dell Optiplex 3010
¤ Added machine Lenovo-T420s
¤ Added machine Lenovo-T430s

¤ Changes in build/boot-images/templates/refind/default/refind.conf
    1. Added the line "scanfor manual,internal,external,optical" in order to make the "stanzas" section boot before the autodiscovered boot partitions.
    2. Added the line "default_selection Thinstation" in order to make it boot then "Thinstation" menu selection as default

       Default if nothing is stated in the refind.conf file is "last booted operating system" and I hade issues with "kernel panic" since my computer scanned and found the EFI image autmatically. This resolves that issue.

¤ Changes in the package base
    1. Corrected a typo in thinstation.packages
            At least I think it's a typo where a $ was missing before {PASSWORD_ARG}. Citrix didn't work for me (se fix in ica package below about ica.server_first)
    2. Added documentation for NET_FILES_METHOD to inform that wget/can be used and not only tftp/scp (and added http for more user friendly readability option)
       Also added in 

¤ Changes in the package networkmanager
    1. Fixed thinstation parameters/variables for ip-addresses that was not set correctly.
        Changes are in
            /build/packages/networkmanager/build/extra/etc/NetworkManager/dispatcher.d/00-update-status
            /build/packages/networkmanager/build/extra/etc/init.d/NetworkManager
            /build/packages/networkmanager/build/extra/etc/udev/scripts/net.sh

¤ Changes in the package xfwm4
    1. Added parameter to disable/hide the "Suspend" button under the start-menu > Session

¤ Changes in the package ica
    1. Fixed error when you had "SESSION_1_ICA_OPTIONS" set
            added the file "ica.server_first" to /ts/build/packages/ica/build/extra/etc/cmd/ica.server_first
            (see https://sourceforge.net/p/thinstation/mailman/message/29043478/

¤ Added new package local-install
    My main contribution. Lets you have a central managed Thinstation image with version control,
    touch less clients and improves the boot time very much compared to using PXE.

    See documentation both in /ts/build/Documentation/README.local-install and thinstation.conf.sample

¤ Added new package custom-background
    Lets you set/change the background from the configuration files. My use case is that in the default build I
    have a background displaying an error message (you didn't receive your configuration files) and in
    thinstation.conf.network we set the background to the "normal" background image. Finally in
    thinstation.conf.group.test I set a different background informing the user/admin that this computer is part
    of a testgroup with different configurations (see local-install for more info.)

¤ Added new package custom-idle
    Lets you control when to shutdown or reboot Thinstation clients. If none of the processes/applications defined
    shut down the computer if it has been idle for more than X minutes. You can also set it to reboot the computer
    every day at a specific time. My main purpose was to shut down computers not in use and also to ensure that
    new Thinstation images (local-install) was upgraded to all computers.

¤ Added new package hdd-spindown
    With local-install the local disk is only used during boot. With this package we spin down ("stop") the rotating
    disk which both lower the noise of the computer (we had som issues with vibration causing irritating noise for
    the users) and expands the lifetime of the hard disk.

¤ Added new package set-resolution
    Lets the user both change, but more importantly save the resolution to the local config file. This is used in
    conjunction (but not necessarily) with the local-install package.

    This package also configures multi monitor setup to either expand or mirror monitors.

### CODE REVIEW

**Comment by Thinstation** [comment]
There is a lot of good stuff in here, thank you so much for contributing back to the project, the more the merrier. A couple of things we simply can't allow though. 
#1 Can't bypass /dev/random - I think this can be solved another way.
#2 Don't change the included packages in the default config. Several configs are available, but default is where we start people out, so they can at least make something without getting overwhelmed(We try).

I think we can massage this PR a bit, and get it included in master and hopefully in 6.1. I hesitate to push anything this size to Stable.

**Comment by MarcusEyre** [comment]
I have now tested with Citrix Receiver 13.3. and the issue with entropy does not exist any more (perhaps it was some error in my previous build image). I have now removed that part from ica_receiver_config.sh and will update this pull request (see next question).

regarding the config file. I can revert to the original and just add my packages as outcommented lines but the following I really suggest that we add the following in default config:

- set-resolution, by including the package as default will make multi monitor supported and function i a good manner compared to how it is now in my opionion.

- netfiles, we dont need to include it by default but add the line outcommented to show that this can be included and provide great functionality (central management)

- param bootimages, include syslinux and refind as default. In fact why not all since I guess that most users will not find this parameter in an easy way (I hade to look in the build script to see why refind wasn't created and thereby see that I could simply add it to the bootimages param.)


I will revert /ts/build/build.conf.example and /ts/build/thinstation.conf.buildtime and just include my packages/changes as commented lines and update this pull request.

/Marcus

**Comment by Thinstation** [comment]
If you can get all your changes in without changing the default experience, I'll merge with Stable/Master/6.1-Unstable.
I won't make you do it alone. Thank you again for your contributions.

**Comment by Thinstation** [comment]
Oh, and what's with libc in ICA?

**Comment by MarcusEyre** [comment]
if you run /opt/Citrix/ICAClient/util/hdxcheck.sh you can see that it complains about a few things one of them being libc not installed why I copied it from /lib in the build environment (or from some other package, can't remember). It still complains about libcap and ligjpeg or something if i remember correctly. I wasn't able to fix that since about there my knowledge of linux unfortunatly ends (installing libs, compiling source and installing new compiled programs)

The result is that Windows Media Direction in Citrix HDX does not work with Thinstation and neither does Skype with HDX Optimization Pack. That will be my next challange to get working on Thinstation...

Was it wrong of me to just copy the libc- files?

**Comment by Thinstation** [comment]
We also need to revert changes to build.urls. Some interesting experiments, but mostly not a good default. Some of the version updates can be kept, but bited'ness should go

ts/build/packages/chromium/build/extra/bin/chromium, Can't put the homepage in the script. The homepage is normally set per session via an init.d/ script. TS_GLOBAL may not be necessary here.

**Comment by MarcusEyre** [comment]
I have now reverted to the original config files for build.conf.example, build.urls, thinstation.build.example but with the following changes:

**build.urls**
Completly reverted, do note however that the only browser I got working with ./build --kernel 64 (needed for UEFI firmware) was Chromium

The url for Flash does not work. I could not find a working url and you need to download the file manually first. The flash url in build.urls remains broken...


**build.conf.example**
Added (as comments) my new packages and some others like chromium, ca-bundle, openssl etc.
Included the following packages/changes by default:

- set-resolution This will give a good multi monitor support by default

- param bootimages, include refind 

- param bootserver, this was not included in build.conf.example but it is used by the build script when the pxe images config files are created. 


**thinstation.conf.buildtime**
Added the parametes for SET_RESOLUTION_MULTIMONITOR to make the default behavior to mirror and scale if the monitors have different resolutions.


In your previous comment you say I should'nt change the ts/build/packages/chromium/build/extra/bin/chromium to include the $CHROME_HOMEPAGE parameter and that this is done via session. How is that done? By adding chromium package an Icon appear on the desktop and that leads to thinstation homepage. How do I change that (if not using my customization of the bin script?)

**Comment by MarcusEyre** [comment]
I understand that you might have other things to do (no rush) but are there anything more I need to do before you can approve this pull request into the 5.5-Stable branch (or master/6.1 as you mention)? Just so I know if I need to change something more...

Kind regards
Marcus

**Comment by Thinstation** [comment]
I think your o.k., I will get to this, it's just big and I have much to do. ;)

**Pull request merged**
