### PR TITLE
Update network_files

### PR DESCRIPTION
**Pull request by shweew**
Changeover of catv by cat for the correct loading of cyrillic from configuration files.

### CODE REVIEW

**Comment by shweew** [comment]
**sed -e 's/\^M//g'** deletes ^M

**Comment by Thinstation** [comment]
Depends on version of sed.

**Comment by Thinstation** [comment]
There are a few weird things in TS, written a certain way to accommodate the quirks between full size utils and busy box versions. I wanted to rewrite them with sed -i, but never worked it all out.

**Comment by shweew** [comment]
Then for what **catv** transfers an output in **sed - e 's/\^M//g'**?

**Comment by Doncuppjr** [comment]
Some TS users adjust their conf files on windows machines. When they do this, all the line endings are replaced with ^M. The catv is for converting these line endings back to Unix.


Sent from Yahoo Mail for iPhone


On Tuesday, January 30, 2018, 7:13 AM, Dmitriy Shweew <notifications@github.com> wrote:


Then for what catv transfers an output in sed - e 's/^M//g'?

**Pull request closed without merging**
