### PR TITLE
permission and softlink fixed in ocsinventory

### PR DESCRIPTION
**Pull request by trentasis**
incorrect permission ocsinventory.init and rc5. softlink incorrect

### CODE REVIEW

**Comment by trentasis** [comment]
please can you upload chmod 755 ocsinvnetory.ini and remove ald softlink to master branch?
thanks

**Comment by Thinstation** [comment]
Fixed?

**Comment by trentasis** [comment]
with this pull request commit should be fixed...  only required 
chmod 55 ocsinvnetory.init 
remove broken link from rc5.d

Can you commit?

Thanks

**Comment by Thinstation** [comment]
I think this is fixed in master and normalized for thinstation. Can you confirm?

**Comment by trentasis** [comment]
3 days ago I have made some tests, only two problems described are in
master branch
Please make this in master branch and this will solve this problem:
- chmod 755 ocsinvnetory.init
- remove broken link from rc5.d

Only this changes, with this all works, please can you correct in 5.4
branch?

Thanks

2016-06-10 17:44 GMT+02:00 Thinstation <notifications@github.com>:

**Comment by Doncuppjr** [comment]
I already chmod 755, and moved ocsinventory.init to ocsinventory, and fixed links.

Sent from Yahoo Mail on Android 
 
  On Fri, Jun 10, 2016 at 9:31 AM, trentasis<notifications@github.com> wrote:   3 days ago I have made some tests, only two problems described are in
master branch
Please make this in master branch and this will solve this problem:
- chmod 755 ocsinvnetory.init
- remove broken link from rc5.d

Only this changes, with this all works, please can you correct in 5.4
branch?

Thanks

2016-06-10 17:44 GMT+02:00 Thinstation <notifications@github.com>:

**Comment by trentasis** [comment]
I don't see any change in last 10 day in master branch related with this
bugs, can you update in 5.4?
Thanks

2016-06-10 18:33 GMT+02:00 Donald A. Cupp Jr. <notifications@github.com>:

**Comment by Doncuppjr** [comment]
https://github.com/Thinstation/thinstation/commit/b48fd0249e6617cc55dcaa2902f682f1358fb93b 

    On Friday, June 10, 2016 10:01 AM, trentasis <notifications@github.com> wrote:
 

 I don't see any change in last 10 day in master branch related with this
bugs, can you update in 5.4?
Thanks

2016-06-10 18:33 GMT+02:00 Donald A. Cupp Jr. <notifications@github.com>:

**Comment by trentasis** [comment]
Perfect!
Can you push to 5.4 branch?
Thanks

2016-06-10 19:08 GMT+02:00 Donald A. Cupp Jr. <notifications@github.com>:

**Comment by Doncuppjr** [comment]
done
 

    On Friday, June 10, 2016 10:18 AM, trentasis <notifications@github.com> wrote:
 

 Perfect!
Can you push to 5.4 branch?
Thanks

2016-06-10 19:08 GMT+02:00 Donald A. Cupp Jr. <notifications@github.com>:

**Comment by trentasis** [comment]
Solved with https://github.com/Thinstation/thinstation/commit/5e9c35ab9786a64fc78efb4e00f70d773be9620b

Thanks

**Pull request closed without merging**
